### ISSUE TITLE
CustomEnchants::getName() must be compatible with pocketmine\item\enchantment\Enchantment::getName()

### ISSUE THREAD

**Issue by isoz** [MCPEPIG/PiggyCustomEnchants#1]
Error: Declaration of PiggyCustomEnchants\CustomEnchants\CustomEnchants::getName() must be compatible with pocketmine\item\enchantment\Enchantment::getName(): string
File: /plugins/PiggyCustomEnchants/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants
Line: 170
Type: E_COMPILE_ERROR

**Comment by MCPEPIG** [comment]
Are you using latest PMMP on master?

**Comment by isoz** [comment]
No. I'm using Genisys, what should I look for?

**Comment by MCPEPIG** [comment]
This is for PMMP not Genisys.

**Comment by MCPEPIG** [comment]
This should now work for Genisys.
