### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by EpicDF** [MCPEPIG/PiggyCustomEnchants#3]
Hi, I was wondering if this is compatible with the 3.0 API and PE 1.0.7? If so, is there a plugin packager I don't know about that already works, since you don't have a .phar file? I would like to use this on my Tesseract server but don't know where to get a DevTools plugin. Thanks for the help!

**Comment by MCPEPIG** [comment]
https://poggit.pmmp.io/ci/MCPEPIG/PiggyCustomEnchants/PiggyCustomEnchants/Dev:5

**Comment by MCPEPIG** [comment]
This might not work with Tesseract as it was tested only in PMMP.
