### ISSUE TITLE
Is tesseract supported?

### ISSUE THREAD

**Issue by Dragonblitz10** [MCPEPIG/PiggyCustomEnchants#4]
Tesseract Crash Dump Wed May 3 20:13:55 CEST 2017

Error: Declaration of PiggyCustomEnchants\CustomEnchants\CustomEnchants::getName() must be compatible with pocketmine\item\enchantment\Enchantment::getName(): string
File: /PiggyCustomEnchants-master/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants
Line: 210
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : PiggyCustomEnchants v1.0.0

Code:
[201]      */
[202]     public function setLevel($level)
[203]     {
[204]         $this->level = (int)$level;
[205] 
[206]         return $this;
[207]     }
[208] 
[209] 
[210] }
[211] 
[212] 
[213] 
[214] 
[215] 
[216] 
[217] 
[218] 
[219] 
[220] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 107; API 3.0.1]
uname -a: Linux ca25.server.pro 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
PHP version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

**Comment by MCPEPIG** [comment]
no.

**Comment by MCPEPIG** [comment]
This should now work for Tesseract.
