### ISSUE TITLE
Some Bugs.

### ISSUE THREAD

**Issue by ZaneWalter** [MCPEPIG/PiggyCustomEnchants#7]
Hi. First of all this is an awesome plugin. Thanks for sharing. 
There are some bugs that I wanted to point out so they could be fixed.

1. If you have an item that is custom enchanted then then you cannot drop it to give it to another player. 
2. Item drops are late. And if the item drops one cannot pick it up. It comes in the inventory for half a         		second and then disappears.
3. The  name of the enchantment does not appear on the enchanted item.

None the less your plugin is the best. I am not complaining in anyway as mentioned earlier. I am just reporting so the errors could be fixed at the earliest.

**Comment by MCPEPIG** [comment]
Hmm, I'm not experiencing any of these issues. Are you using the latest version?

**Comment by Dragonblitz10** [comment]
He Is most likely using the first build as you experience the first two with it not the third one

**Comment by ZaneWalter** [comment]
As a matter of fact im using the latest version on Tesseract. Also there is also another bug. The custom enchanted armour cannot be used. If one tries to put the armour on himself it disappears and falls to the ground.

**Comment by Aericio** [comment]
Can you please test this on pmmp and not third-party "spoons"?

**Comment by ZaneWalter** [comment]
I tested this on pmmp. It works fine except for out of 89 plugins only 10 worked.  But can you please fix this for tesseract.

**Comment by MCPEPIG** [comment]
We currently do not support Tesseract.
