### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by moneymill2400** [MCPEPIG/PiggyCustomEnchants#8]
I'm running a mcpe server and this looks like a really good plugin and I was wondering how I can run this plugin on my server

**Comment by Aericio** [comment]
put this plugin in your plugins folder and do /customenchant

**Comment by moneymill2400** [comment]
Are you sure

**Comment by moneymill2400** [comment]
Do you put the whole zip or he custom enchant file

**Comment by Aericio** [comment]
...

**Comment by Aericio** [comment]
https://poggit.pmmp.io/ci/MCPEPIG/PiggyCustomEnchants grab the latest .phar builds here.
